### ISSUE TITLE
Integrate a maintained multi-select/tag/search and typeahead Frontend-component

### ISSUE THREAD

**Issue by BryceStevenWilley** [LemmaLegalConsulting/docassemble-tclpgoogledocsmerger#2]
> https://mdbootstrap.com/docs/standard/extended/multiselect/ search interface here looks great
MIT licensed
BUT the specific input is a "pro" feature

>  https://github.com/andreww1011/filter-multi-select looks quite close but isn't working right inside Docassemble. probably some Docassemble JS is overriding it?
- @nonprofittechy

**Comment by BryceStevenWilley** [comment]
General docassemble multiselects are in now. Still need them to be flashier, though I wasn't sure where Quinten ended up here, so I don't know where to start.

**Comment by nonprofittechy** [comment]
Fixed in #8
