### ISSUE TITLE
Add simple DAStore analytics

### ISSUE THREAD

**Issue by BryceStevenWilley** [LemmaLegalConsulting/docassemble-tclpgoogledocsmerger#25]
* what was searched for
* what clauses were in the Airtable
* what clauses were actually found in the GDrive
* IP location
  * this is the tricky one. Maybe try https://pypi.org/project/IP2Location/?

**Comment by nonprofittechy** [comment]
The ip2location webservice I'm trying is actually scarily precise...put me in North Cambridge. So we might want to consider adding some fuzzing? That's unlikely to be relevant information.

**Comment by BryceStevenWilley** [comment]
I think I raised this in the PR, but do we even need lat/long? Should city / postal be good enough? Otherwise I think the next best option is rounding lat long to some fixed discretization,

**Comment by nonprofittechy** [comment]
Post code across dozens of countries sounds unmaintainable to me to
actually learn anything. I think lat/long will scale better. Just want to
think about precision.

My case might have just been coincidentally close to my real address.
