### ISSUE TITLE
Strip extra whitespace off values

### ISSUE THREAD

**Issue by BryceStevenWilley** [LemmaLegalConsulting/docassemble-tclpgoogledocsmerger#4]
Pandas is very difficult to work with when the elements are lists. Having trouble striping white space off of the strings that are in the lists, still need to do that.

**Comment by nonprofittechy** [comment]
Is this syntax helpful? https://www.geeksforgeeks.org/pandas-strip-whitespace-from-entire-dataframe/

**Comment by BryceStevenWilley** [comment]
The converters are useful, since I'm already doing a lot of processing of each column. I'll try that.
